---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # Patched omnibus installer - nothing unique to IPS, just has omnitruck PR #72 installed
  chef_omnibus_url: https://svn.omniti.com/chef-install/install.sh

platforms:
  - name: omnios-008
    driver:
      box: omnios-r151008j-r1

  - name: omnios-012
    driver:
      box: omnios-r151012

suites:
  - name: default
    run_list:
      - recipe[ips::test_publisher]
    attributes:
